# Generated by Django 4.1.4 on 2023-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='filling_the_bed',
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_size',
            field=models.CharField(default=True, max_length=255, verbose_name='Размеры спального места (ШхД)'),
        ),
        migrations.AddField(
            model_name='sofa',
            name='bed',
            field=models.BooleanField(default=True, verbose_name='Наличие спального места'),
        ),
        migrations.AddField(
            model_name='sofa',
            name='bed_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры спального места (ДхГ)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размеры (ШхДхВ)'),
        ),
    ]
